apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nexus-local
  hostPath:
    path: /mnt/data/nexus
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data
  namespace: bootcamp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nexus-local
  resources:
    requests:
      storage: 2Gi