apiVersion: v1
# Expose an application running in your cluster behind a single outward-facing endpoint, even when the workload is split across multiple backends.
kind: Service
metadata:
  name: nexus
  namespace: bootcamp
  labels:
    app: nexus
spec:
  type: ClusterIP
  # Tells K8s "Send traffic to pods that have the lable app: nexus"
  selector:
    app: nexus
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
